//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenClawAgent.Properties
{
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    [global::System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default => defaultInstance;

        [global::System.Configuration.UserScopedSetting]
        [global::System.Diagnostics.DebuggerNonUserCode]
        [global::System.Configuration.DefaultSettingValue("False")]
        public bool TrayHintShown
        {
            get => (bool)this["TrayHintShown"];
            set => this["TrayHintShown"] = value;
        }

        [global::System.Configuration.UserScopedSetting]
        [global::System.Diagnostics.DebuggerNonUserCode]
        [global::System.Configuration.DefaultSettingValue("True")]
        public bool MinimizeToTray
        {
            get => (bool)this["MinimizeToTray"];
            set => this["MinimizeToTray"] = value;
        }

        [global::System.Configuration.UserScopedSetting]
        [global::System.Diagnostics.DebuggerNonUserCode]
        [global::System.Configuration.DefaultSettingValue("False")]
        public bool StartMinimized
        {
            get => (bool)this["StartMinimized"];
            set => this["StartMinimized"] = value;
        }
    }
}
